name: neccton-bb
channels:
  - conda-forge
dependencies:
  - python=3.9
  - fortran-compiler
  - netcdf-fortran
  - jupyterlab
  - cmake
  - numpy
  - matplotlib
  - scipy
  - ipympl
  - netcdf4
  - pyyaml
